name: jazzve_web
description: "Jazzve web tool"
publish_to: 'none'

version: 1.0.0+12

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_bloc: ^8.1.6
  shared_preferences: ^2.3.2
  flutter_localizations:
    sdk: flutter
  intl: any
  http: ^1.2.2
  freezed: ^2.5.7
  freezed_annotation: ^2.4.4
  json_annotation: ^4.9.0
  flutter_launcher_icons: ^0.14.1
  package_info_plus: ^8.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0
  build_runner: ^2.4.13
  json_serializable: ^6.8.0

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/


